name: matomo
icon: matomo
title: Matomo

services:
- name: matomo
  title: Matomo
  service: matomo
  required: true
  links:
  - name: db
    service: mariadb

- name: nginx
  title: Nginx
  service: php-nginx
  required: true
  containers:
  - name: nginx
    env:
    - name: NGINX_VHOST_PRESET
      value: matomo  
  links:
  - name: backend
    service: matomo

- name: mariadb
  title: MariaDB
  service: mariadb
  volumes:
  - name: data
    size: 20
