name: matomo
icon: matomo
title: Matomo

services:
- name: matomo
  title: Matomo
  service: matomo
  required: true
  links:
  - name: db
    service: mariadb
  - name: sendmail
    service: opensmtpd

- name: nginx
  title: Nginx
  service: matomo-nginx
  required: true
  links:
  - name: backend
    service: matomo

- name: mariadb
  title: MariaDB
  service: mariadb
  volumes:
  - name: data
    size: 20

- name: opensmtpd
  required: false
  title: OpenSMTPD
  service: opensmtpd

- name: valkey
  required: false
  disabled: true
  title: Valkey
  service: valkey
